### ISSUE TITLE
Compiling pk1 ... Warning message:

### ISSUE THREAD

**Issue by kenujen** [metrumresearchgroup/pbpk-qsp-mrgsolve#7]
Hi Kyle, 
Thanks for the package and tutorial. I got this error message when compiling pk1. Any assistance would be greatly appreciated.

<R> mod <- mread('pk1', modlib())

Compiling pk1 ... Warning message:
running command 'make -f "C:/PROGRA~1/R/R-34~1.4/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.4/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="pk1-mread-source.dll" WIN=64 TCLBIN=64 OBJECTS="pk1-mread-source.o"' had status 127 
-------------
Error: there was a problem building the model.﻿

**Comment by kylebmetrum** [comment]
Hi @kenujen  - 

The `status 127` error means that R cannot find the Rtools tool chain.  I thought we had this worked out at ASCPT, so not sure what changed in the meantime. 

Can you share again your `sessionInfo`?  

Also, we need to know what is your `Sys.getenv("PATH")`

**Comment by kylebmetrum** [comment]
@kenujen Just re-install Rtools.  You have to be very careful and click the box (opt-in) when the installer asks if it can change your path.  

After you re-install Rtools, restart Rstudio (from scratch).  You might have to restart your computer too.  

When Rstudio starts up again, check the PATH to make sure R can find Rtools.

**Comment by kenujen** [comment]
Thanks Kyle!
That fixed it.
